### PR TITLE
Fix #6047: DNS timeouts, shared DnsResolver, avoid hangs when resolving DNS, log exception traces

### LINKED ISSUE #6047: Frequent timeouts and hanging on requests when executed without internet access
The external_network option is not respected fully, and the code does not block external network access properly on at least one (unknown) endpoint. Java stack trace, unfortunately, does not show any application frames. When accessing the control panel, I get:

```java
INFO  20:26:47.070 [pool-1-thread-1] Exception in thread "pool-1-thread-1" java.util.concurrent.CompletionException: java.net.ConnectException
INFO  20:26:47.070 [pool-1-thread-1]    at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
INFO  20:26:47.070 [pool-1-thread-1]    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(Unknown Source)
INFO  20:26:47.070 [pool-1-thread-1]    at java.base/java.util.concurrent.CompletableFuture.thenCompose(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.base/java.util.concurrent.CompletableFuture.handle(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.base/java.lang.Thread.run(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1] Caused by: java.net.ConnectException
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.Http2Connection.createAsync(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.ExchangeImpl.get(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.Exchange.establishExchange(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Unknown Source)
INFO  20:26:47.071 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Unknown Source)
INFO  20:26:47.072 [pool-1-thread-1]    ... 13 more
INFO  20:26:47.072 [pool-1-thread-1] Caused by: java.nio.channels.UnresolvedAddressException
INFO  20:26:47.072 [pool-1-thread-1]    at java.base/sun.nio.ch.Net.checkAddress(Unknown Source)
INFO  20:26:47.072 [pool-1-thread-1]    at java.base/sun.nio.ch.Net.checkAddress(Unknown Source)
INFO  20:26:47.072 [pool-1-thread-1]    at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(Unknown Source)
INFO  20:26:47.072 [pool-1-thread-1]    at java.base/sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
INFO  20:26:47.072 [pool-1-thread-1]    at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(Unknown Source)
INFO  20:26:47.072 [pool-1-thread-1]    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
INFO  20:26:47.072 [pool-1-thread-1]    ... 22 more
```

And then the panel loads. But this is after 30 seconds, which is probably the default DNS timeout on my machine's environment for JDK. This times out TV navigation and makes browser navigation experience terrible.

UMS.conf:

```ini
jwt_secret = snipped_for_security
cred.path = /home/userhome/.config/UMS/UMS.cred
language = en-US
engines = FFmpegVideo,MEncoderVideo,tsMuxeRVideo,VLCVideo,FFmpegAudio,tsMuxeRAudio,FFmpegHlsVideo,FFmpegWebVideo,VLCWebVideo,VLCVideoStreaming,MEncoderWebVideo,VLCAudioStreaming,DCRaw,youtubeDl
engines_priority = FFmpegVideo,FFmpegHlsVideo,MEncoderVideo,tsMuxeRVideo,VLCVideo,FFmpegAudio,tsMuxeRAudio,FFmpegWebVideo,youtubeDl,VLCWebVideo,VLCVideoStreaming,MEncoderWebVideo,VLCAudioStreaming,DCRaw
was_youtube_dl_enabled_once = true
hide_advanced_options = false
scan_shared_folders_on_startup = false
scan_shared_folders_on_startup = false
run_wizard = false
show_info = false
ffmpeg_available_gpu_acceleration_methods = none,auto,vdpau,cuda,vaapi,qsv,drm,opencl,vulkan,amf
uuid = 69fb9cbc-2b23-4064-a0c9-e7ec0294e8a3
auto_update = false
server_name = UMS UserBox
external_network = false
network_interface = wlan0
use_api_info = false
audio_thumbnails_method = 0
generate_thumbnails = false
image_thumbnails = false
dvd_isos_thumbnails = false
alternate_thumb_folder =
web_player_enable = false
web_gui_on_start = true
chromecast_extension = false
chromecast_debug = false
managed_playlist_folder =
nextcp_api_key =
```

I suggest properly logging stack traces on network access points, so this can be traced to the source and fixed. This is making it impossible to use UMS offline from my box by default, which is the usecase I will use it the most...

### PR DESCRIPTION
**Pull request by henry701**
Addresses https://github.com/UniversalMediaServer/UniversalMediaServer/issues/6047 (timeouts and hanging when no network access is available and the DNS resolver is slow).

## Changes

- **DnsResolver** (new): Single shared executor for all DNS/reverse-DNS with configurable timeouts. No caching. All timeouts and errors are logged with call context and stack traces. **Timeouts are only applied when `dns_resolution_timeout_enabled` is true** (see Configuration flags below).
- **NetworkDeviceFilter**: Uses `DnsResolver.resolveReverse()` for hostname matching
- **JUPnPDeviceHelper**: Uses `DnsResolver.resolveByName` / `resolveAllByName`
- **JavaHttpClient**: Connect (5s) and response (15s) timeouts on all HTTP calls **only when `http_timeout_enabled` is true** (see Configuration flags below); otherwise no timeouts (legacy behavior).
- **HttpServletHelper**: `getInetAddress` / `deny` / `isLocalhost` use `parseAddressLiteral()` (Guava `InetAddresses.forString`) so remote-address handling does not trigger DNS; request logging uses `getRemoteAddr()` instead of `getRemoteHost()` to avoid DNS resolution.
- **SpeedStats**: Resolves hostname in parallel on background thread, updates cache under IP and hostname in `whenComplete`. Also, add a guard for when all pings fail (used to cause division by zero).
- **UmsConfiguration**: `getHostName()` improved logging on failure. New **`dns_resolution_timeout_enabled`** (default false) and **`http_timeout_enabled`** (default false): when true, DnsResolver / JavaHttpClient use timeouts; when false, legacy blocking behavior. Getters/setters and defaults in config schema; both exposed in web UI under General → External outgoing traffic (advanced).
- **Tests**: **DnsResolverTest** (null/empty, loopback, IP-only, unknown host; resolveByName/resolveAllByName). **NetworkDeviceFilterTest** (getDisplayName, HostNamePredicate, timeout-bounded match for IP-only address).

## New Configuration Flags (Backward Compatibility)

Configurable timeouts for external DNS and HTTP (General → **External outgoing traffic**, advanced):

| Key | Type | Default | Description |
|-----|------|---------|-------------|
| `dns_resolution_timeout_enabled` | boolean | `false` | Enable a timeout for DNS and reverse-DNS resolution. When off, resolution blocks until the OS resolver completes. |
| `dns_resolution_timeout_ms` | int | `5000` | Timeout in ms for DNS resolution. Used only when `dns_resolution_timeout_enabled` is true. Range 1–120000. |
| `http_timeout_enabled` | boolean | `false` | Enable connect and response timeouts for outgoing HTTP requests (e.g., thumbnails, API calls). |
| `http_connect_timeout_seconds` | int | `5` | HTTP connect timeout in seconds. Used only when `http_timeout_enabled` is true. Range 1–300. |
| `http_response_timeout_seconds` | int | `15` | HTTP response (read) timeout in seconds. Used only when `http_timeout_enabled` is true. Range 1–600. |

- **DNS:** `DnsResolver` reads timeout from config; callers do not pass timeouts. When the flag is off, resolution has no timeout. Errors/timeouts are logged with stack traces (no call-context parameter).
- **HTTP:** `JavaHttpClient` applies connect/response timeouts when the flag is on; otherwise, no timeout.

The new options are documented with the other configuration flags (UmsConfiguration getters/setters and defaults in the config schema). They are exposed in the web UI under **General** → **External outgoing traffic** (advanced settings). Users who experience hangs (e.g., issue 6047) can turn them on; others can leave them off.

### CODE REVIEW

**Comment by SubJunk** [comment]
Thanks for this, I am about to go on holiday for the week but will review asap

**Comment by henry701** [comment]
No hurrry at all! Thank you for maintaining UMS. It's the only media server among 5 that worked with my father's old TV.

File: src/main/java/net/pms/network/NetworkDeviceFilter.java [hunk 1]
```diff
@@ -188,15 +177,44 @@ private static synchronized boolean isAllowed(InetAddress addr, boolean logging)
...
+	static String getDisplayName(InetAddress addr) {
+		if (addr.isLoopbackAddress()) {
+			return "localhost";
+		}
+		String text = addr.toString();
+		int separator = text.indexOf('/');
+		if (separator > 0) {
+			return text.substring(0, separator);
+		}
+		return addr.getHostAddress();
```
Comment (henry701) [inline src/main/java/net/pms/network/NetworkDeviceFilter.java]: Behavior changed slightly, returns the IP address instead of performing reverse DNS through `getHostName`. If thats an issue, we can use `DnsResolver.resolveReverse` instead to preserve the old behavior.

File: src/main/java/net/pms/external/JavaHttpClient.java [hunk 2]
```diff
@@ -60,13 +108,11 @@ private JavaHttpClient() {
 	 */
 	public static byte[] getBytes(String uri) throws IOException {
 		try {
-			HttpRequest request = HttpRequest.newBuilder()
-					.uri(new URI(uri))
+			HttpRequest request = addRequestTimeout(HttpRequest.newBuilder()
+					.uri(new URI(uri)))
```
Comment (henry701) [inline src/main/java/net/pms/external/JavaHttpClient.java]: Missing refactor, instead of repeating the addRequestTimeout line, should have a method that receives the URI as a string and does:

```java
var builder = HttpRequest.newBuilder().uri(new URI(uri));
if (isTimeoutEnabled()) {
			int sec = Math.max(1, getResponseTimeoutSeconds());
			builder.timeout(Duration.ofSeconds(sec));
		}
		return builder;
```

And then use that instead.

File: src/main/java/net/pms/network/NetworkDeviceFilter.java [hunk 3]
```diff
@@ -188,15 +177,44 @@ private static synchronized boolean isAllowed(InetAddress addr, boolean logging)
...
+				LOGGER.info("IP Filter: Access denied to {}", getDisplayName(addr));
 			}
 		}
 
 		return allowedByDefault;
 	}
 
+	private static JsonObject createDevice(InetAddressSeen addrSeen) {
+		JsonObject device = new JsonObject();
+		device.addProperty("hostName", getDisplayName(addrSeen.addr));
```
Comment (henry701) [inline src/main/java/net/pms/network/NetworkDeviceFilter.java]: DnsResolver.resolveReverse` instead of `getDisplayName`

File: src/main/java/net/pms/external/JavaHttpClient.java [hunk 4]
```diff
@@ -42,10 +44,61 @@ public class JavaHttpClient {
...
+
 	private JavaHttpClient() {
+		throw new UnsupportedOperationException("This class is not meant to be instantiated.");
+	}
+
+	private static boolean isTimeoutEnabled() {
+		try {
+			return PMS.getConfiguration() != null && PMS.getConfiguration().isHttpTimeoutEnabled();
+		} catch (Exception e) {
+			return false;
```
Comment (SubJunk) [inline src/main/java/net/pms/external/JavaHttpClient.java]: It would be good to log the exceptions in here instead of swallowing them, and the same in the other catches in this file

**Review by SubJunk — CHANGES_REQUESTED** [review]
This looks good, you have matched the codestyle well and added tests, it would just be good to add logging for exceptions

**Comment by henry701** [comment]
Fair, those config helper swallows slipped by even after I solved others. I'll adjust tomorrow.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SubJunk** [comment]
This looks good from a code perspective, I'll test it soon

**Comment by SubJunk** [comment]
I didn't find any bugs with some light testing and general use, thanks!
