### PR TITLE
Fix external subtitles streaming if renderers do not have any "se" defined in Supported lines

### LINKED ISSUE #2052: Embedded subtitles used instead of external
User jkwu mentioned a regression in v8+ at https://www.universalmediaserver.com/forum/viewtopic.php?f=9&t=14007&start=10#p41144

@valib

### PR DESCRIPTION
**Pull request by SubJunk**
Fixes #2052

### CODE REVIEW

File: src/main/java/net/pms/configuration/FormatConfiguration.java [hunk 1]
```diff
@@ -198,10 +198,10 @@
 		private String mimeType;
 		private String videoCodec;
 		private String supportLine;
-		/** List of embedded subs supported by renderer defined in the Supported line in the renderer.conf */
-		private String embeddedSubs;
-		/** List of external subs supported by renderer defined in the Supported line in the renderer.conf */
-		private String externalSubs;
+		// List of embedded subs supported by renderer defined in the Supported line in the renderer.conf
+		private String supportedEmbeddedSubtitlesFormats;
+		// List of external subs supported by renderer defined in the Supported line in the renderer.conf
```
Comment (Nadahar) [inline src/main/java/net/pms/configuration/FormatConfiguration.java:203]: This change means it's no longer a JavaDoc, and thus won't show up when you hover over the variable in IDE's etc.

Comment (SubJunk) [reply src/main/java/net/pms/configuration/FormatConfiguration.java:203]: That's true, but I almost removed those comments since the new variable name already describes it IMO

File: src/main/java/net/pms/configuration/FormatConfiguration.java [hunk 2]
```diff
@@ -198,10 +198,10 @@
 		private String mimeType;
 		private String videoCodec;
 		private String supportLine;
-		/** List of embedded subs supported by renderer defined in the Supported line in the renderer.conf */
-		private String embeddedSubs;
-		/** List of external subs supported by renderer defined in the Supported line in the renderer.conf */
-		private String externalSubs;
+		// List of embedded subs supported by renderer defined in the Supported line in the renderer.conf
```
Comment (SubJunk) [inline src/main/java/net/pms/configuration/FormatConfiguration.java:201]:
```suggestion
```

File: src/main/java/net/pms/configuration/FormatConfiguration.java (hunk 1 above)
Comment (SubJunk) [inline src/main/java/net/pms/configuration/FormatConfiguration.java:203]:
```suggestion
```

**Comment by SubJunk** [comment]
@valib the user has reported that this fixed their bug. They have also reported another bug it did not fix, but I would like to merge this and then work on the other one separately, to maintain focus. Please review

**Review by valib — APPROVED** [review]
