### PR TITLE
main fix 5203

### LINKED ISSUE #5203: Regression: support for Windows short names
In the past we would support very long file names (at least on Windows) by falling back to short names, but now the files just are not added. I had to rename them to be shorter so UMS would see them

### PR DESCRIPTION
**Pull request by SurfaceS**
fix #5203

# Description of code changes
use of Win32 file prefixing and conventions
refactoring `getShortFileNameIfWideChars` to `getSystemPathName`
refactoring `getShortPathNameW` to `getSystemPathName`

### CODE REVIEW

File: src/main/java/net/pms/platform/windows/WindowsUtils.java [hunk 1]
```diff
@@ -108,37 +105,21 @@ public File getKLiteFiltersDir() {
...
-				int r = Kernel32.INSTANCE.GetShortPathNameW(pathname, test, test.length);
-				if (r > 0) {
-					String result = Native.toString(test);
-					LOGGER.trace("Using short path name of \"{}\": \"{}\"", pathname, result);
-					return result;
+	public String getSystemPathName(String path) {
+		if (path != null) {
+			File file = new File(path);
+			String resolved = file.getAbsolutePath();
+			if (resolved.length() > 247) {
```
Comment (SubJunk) [inline src/main/java/net/pms/platform/windows/WindowsUtils.java:112]: Why 247?

Comment (SurfaceS) [reply src/main/java/net/pms/platform/windows/WindowsUtils.java:112]: On Windows the maximum short path is 260 minus 1 (`NUL`) -> 259 char.
But for directories it is 260 minus 12 (8.3 file) minus 1 (`NUL`) to allow for the creation of a file in the directory -> 247.

The long path prefix (`\\?\`) is working with short path as well.
For example, a file like `C:\ProgramData\UMS\UMS.conf` can have `\\?\C:\ProgramData\UMS\UMS.conf` as working path even if it is not more than 259 char (the max for short file path).

So it is no need to check if it is a directory or a file, just prefix as long path if it is more than 247 char.

Comment (SubJunk) [reply src/main/java/net/pms/platform/windows/WindowsUtils.java:112]: Interesting, thanks for explaining. I'll add that explanation as a code comment for future people

Comment (SubJunk) [inline src/main/java/net/pms/platform/windows/WindowsUtils.java:112]:
```suggestion
			/*
			 * On Windows the maximum short path is 260 minus 1 (NUL) -> 259 char.
			 * But for directories it is 260 minus 12 (8.3 file) minus 1 (NUL) to allow for the creation of a file in the directory -> 247.
			  */
			if (resolved.length() > 247) {
```
