### PR TITLE
Fixed failed parsing of files being moved/copied/modified

### LINKED ISSUE #3325: Files locked on filesystem if parsing fails
I think what happens is that if I am copying a group of videos to another hard drive that is monitored by UMS, UMS fails to parse the partial file, and then doesn't release it afterwards.
We have talked before about using a scheduling mechanism for file parsing too, where failed parses are stored temporarily in the database for retry. At the moment we retry after 3 seconds but often more time is needed before there is enough for MediaInfo to use.

### PR DESCRIPTION
**Pull request by SubJunk**
Fixes #3325

### CODE REVIEW

**Comment by SurfaceS** [comment]
I would go for a Timer that parseFileForDatabase entries from a static locked files List<File> (with access lock) each 5 seconds ?

From `LIBRARY_RESCANNER`, if locked and not already exists in the list -> Log and add entry.
On the `parseFileForDatabase` -> Remove locked file entry if it exists in the List.

Then you will be sure that the file will be parsed at end and log only once.

File: src/main/java/net/pms/dlna/RootFolder.java [hunk 1]
```diff
@@ -1445,6 +1445,22 @@ public static final void parseFileForDatabase(File file) {
...
+			return;
+		}
+
+		try (RandomAccessFile srcFile = new RandomAccessFile(file, "rw")) {
+			// no exception happened, so we can continue
+		} catch (Exception e) {
+			/**
+			 * This will happen a lot (every 500ms) for files that are being
+			 * copied/moved. Eventually the last one should succeed.
+			 */
```
Comment (SubJunk) [inline src/main/java/net/pms/dlna/RootFolder.java:1459]:
```suggestion
```

**Review by SurfaceS — DISMISSED** [review]
